### ISSUE TITLE
Configure output

### ISSUE THREAD

**Issue by jsborjesson** [alcesleo/rubocop-config#2]
```yaml
AllCops:
  # Cop names are displayed in offense messages.
  DisplayCopNames: true
  # Style guide URLs are displayed in offense messages.
  DisplayStyleGuide: true
```
